### ISSUE TITLE
How can I send just bytes by rubyserial?

### ISSUE THREAD

**Issue by asiniy** [hybridgroup/rubyserial#27]
IE:

``` ruby
require 'rubyserial'
serialport = Serial.new '/dev/ttyACM0', 9600
serialport.write(0xff) # => exception...
```

**Comment by zankich** [comment]
@asiniy the `write` method accepts a string so you can pack, http://ruby-doc.org/core-2.2.1/Array.html#method-i-pack,  a single byte like this and that should do what you need
```ruby
[0xff].pack('C')
```

**Comment by asiniy** [comment]
@zankich, thx!
