### ISSUE TITLE
Not able to open Comx on Windows 8.1

### ISSUE THREAD

**Issue by nurdymuny** [hybridgroup/rubyserial#28]
Hi 

I am trying to open port on windows 8.1 

irb(main):001:0> require 'rubyserial'
=> true
irb(main):002:0> ser1=Serial.new("COM1")
RubySerial::Exception: ERROR_FILE_NOT_FOUND
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rubyserial-0.2.4/lib/rubyserial/windows.rb:10:in `initialize'
        from (irb):2:in`new'
        from (irb):2
        from C:/Ruby22-x64/bin/irb:11:in `<main>'irb(main):003:0>

I have tried with this way also as mentioned in the below link

https://github.com/hybridgroup/rubyserial/issues/22

has anyone faced this issue on windows 8.1 ?.

thanks

**Comment by zankich** [comment]
@nurdymuny the error message you've posted means that `COM1` does not exist. You can find the list of COM ports by going to `Control Panel->Device Manager->COM`. That should give you the list of COM ports available on your system.

**Comment by nurdymuny** [comment]
Yes , i am able to connect COM1.

Thanks

**Comment by zankich** [comment]
@nurdymuny you're able to connect to the serial port from a different program? Make sure that program does not have an active connection to the serial port when you run your ruby program. You should also check to see if your ruby program has the correct permissions to read from that serial port.

**Comment by deadprogram** [comment]
Closing due to age, please reopen if needed.
