### ISSUE TITLE
Exception Overkill

### ISSUE THREAD

**Issue by kaiserprogrammer** [hybridgroup/rubyserial#31]
Why does RubySerial::Exception inherit from Exception instead of StandardError?

I thought Exception class should be used when further program execution is discouraged or impossible but I get this kind of exception-level for file not found.

**Comment by deadprogram** [comment]
Hi, @kaiserprogrammer seems to me like you have the right idea. Care to submit a PR with that? :)

**Comment by johannes-missbach** [comment]
Hi @deadprogram, I just submitted PR for this. Can you please take a look? :)
